run:
  timeout: 5m
  tests: true

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - goconst
    - gocyclo
    - misspell
    - revive

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow

  gocyclo:
    min-complexity: 20

  goconst:
    min-len: 3
    min-occurrences: 3

  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - goconst
        - gocyclo

    - path: internal/cmd/
      linters:
        - unused
      text: "configEditCmd|configListCmd|configDeleteCmd|defaultCmd"

    - path: internal/cmd/
      linters:
        - revive
      text: "unused-parameter"

    - path: internal/prompt/
      linters:
        - revive
      text: "stutters"

  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
