# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

project_name: pyx

before:
  hooks:
    - rustup default stable
    - cargo install --locked cargo-zigbuild
    - cargo install --locked cargo-xwin
    - sh -c 'ln -sf "$HOME/.cargo/bin/cargo-xwin" "$HOME/.cargo/bin/xwin"'
    - cargo fetch --locked

builds:
  - id: default
    builder: rust
    targets:
      - x86_64-unknown-linux-gnu
      - aarch64-unknown-linux-gnu
      - x86_64-apple-darwin
      - aarch64-apple-darwin

  - id: windows
    builder: rust
    tool: xwin
    command: build
    targets:
      - x86_64-pc-windows-msvc

archives:
  - formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md
      - CHANGELOG.md
      - LICENSE

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
  algorithm: sha256

changelog:
  disable: true

release:
  footer: |

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
