name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  goreleaser:
    name: GoReleaser
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version: stable

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Install Zig
        uses: goto-bus-stop/setup-zig@v2

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: >
            release --clean
            --release-notes <(awk '/^## \\[/{c++; if(c>1)exit; if(c==1){next}} c>0' CHANGELOG.md | tail -c +2)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
